theme: jekyll-theme-midnight
title: "4S Ranch/Del Sur Geoguesser"
description: "Geoguesser focused on the 4S Ranch/Del Sur neighborhood"
gitorg: "https://github.com/chewyboba10/TeamRepo"
google_analytics:
exclude: /path
